### ISSUE TITLE
Option to only index git files

### ISSUE THREAD

**Issue by chr15m** [aerugo/prelude#1]
This seems like a great tool for my workflow, thank you for sharing it. I wonder if it would be possible to add a flag which will only include files from `git ls-files`?

**Comment by chr15m** [comment]
BTW you might like [aish](https://github.com/chr15m/aish) which is a similar bash based tool for getting quick terminal one-liners.

**Comment by aerugo** [comment]
Good idea @chr15m, I will look into it. It shouldn't be very hard.

**Comment by aerugo** [comment]
@chr15m - could you test the version on [feat/gitfeature](https://github.com/aerugo/prelude/tree/feat/gitfeature )? 
I implemented including only files from `git ls-files` with -g option

**Comment by dongyuwei** [comment]
@aerugo I tested your excellent prelude script, the script in main branch is buggy to ignore files/folders in .gitignore, and it's very slow with my simple repo(https://github.com/dongyuwei/temp_mail). 

But, after switch to  [feat/gitfeature](https://github.com/aerugo/prelude/tree/feat/gitfeature), it works great! I hope you publish that version soon, thanks!

**Comment by dongyuwei** [comment]
I also made a simple similar script with `git ls-tree` cmd, which serves the same purpose:
https://gist.github.com/dongyuwei/82e08826e59cd07065ba213a4adf037a
```sh
#!/bin/bash

COMMIT_HASH=$1

git ls-tree --full-tree -r --name-only $COMMIT_HASH | while read -r file; do
    echo "--- $file ---" >> all_files_contents.txt
    git show $COMMIT_HASH:$file >> all_files_contents.txt
    echo "" >> all_files_contents.txt
done
```

**Comment by aerugo** [comment]
@dongyuwei - thanks for testing! I fixed a few other things and pushed a new release. You can install Prelude v0.3 now and use the -g flag to only include files tracked by git.

**Comment by chr15m** [comment]
@aerugo sorry I was not able to check this before you merged, but I just tested and it works great!
